apiVersion: v1
kind: PersistentVolume
metadata:
  name: mydbvol
spec:
  storageClassName: hostpath
  hostPath:
    path: /usr/temp/
  capacity:
    storage: 5Gi
  accessModes:
    - "ReadWriteOnce"
    