apiVersion: v1
kind: Pod
metadata:
    name: pod3
spec:
    containers:
    - image: nginx:1.7.9
      name: web
    - image: mysql:5.7
      name: db
      envFrom:
        - configMapRef:
            name: myconfig

