apiVersion: v1
kind: Pod
metadata:
    name: pod1
spec:
    containers:
    - image: nginx:1.7.9
      name: web
    - image: mysql:5.7
      name: db
      env:
          - name: MYSQL_ROOT_PASSWORD
            value: Pass1234

    
