apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    ## Uses ReplicaSet with Name 'myapp'
    ## And Pods with name myapp
    name: myapp
  ports:
  - port: 8080
    targetPort: 80
    # Port on Node to be mapped to
    # this service
    
