apiVersion: v1
kind: Service
metadata:
  name: myapp2
spec:
  type: NodePort
  selector:
    ## Uses ReplicaSet with Name 'myapp'
    ## And Pods with name myapp
    name: myapp
  ports:
  - port: 8080
    nodePort: 30002
    targetPort: 3000
    
