apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort
  selector:
    ## Uses pods with label 'app=nginx'
    app: nginx
  ports:
  - port: 8080  # Port for SERVICE
    targetPort: 80 # Port for POD/container is 80
    # Port on Node to be mapped to
    # this service
    nodePort: 30001
    
