FROM mcr.microsoft.com/windows/servercore:ltsc2016

RUN mkdir folder1
ENV OWNER Mahendra
ENV APP_PATH /app

## Build an image with name 'env-test'
# $ docker build -t env-test .  
# $ docker inspect env-test
