FROM mcr.microsoft.com/mssql/server:2017-CU8-ubuntu

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Pass@1234

## Build: 
## docker build -t mssql-db .

## Create an Instance
## docker run -d -p 1433:1433 mssql-db
