version: "3"

services:
  app1:
    # please replace ltsc2016 to ltsc2019 in case your windows version is 1903
    image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
    # define the PORT
    ports: 
    - "8080:80"
    networks:
    - net1
  
  app2:
    # please replace ltsc2016 to ltsc2019 in case your windows version is 1903
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    # assign network name (network must exists!)
    networks: 
    - net1
    # Define depencencies between services
    depends_on:
    - app1

networks:
  # define the network name 'net1'
  net1:
      # Network Driver type ( Plugin to be used )
      # the docker default 'bridge' is NOT AVAILABLE on windows
      driver: ics
      # IPAM : The IP Address assignment configuration
      ipam:
        driver: default
        # Network IP Configuration
        config:
        # define the subnet
        - subnet: "172.10.0.0/24"
        