version: "3"

services:
  app1:
    image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
    ports: 
      - 8000:80
    networks:
      - net1
   
# Defined a new private docker network for this deployment
networks: 
  net1:
    driver: transparent

## docker network create net1
## docker run --network net1 -p 8000:80 mcr.microsoft.com/dotnet/framework/samples:aspnetapp
